// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrS9oAk8Myq2U-eyQQsKNlbAFdfqqbF5I',
    appId: '1:867475044073:web:cda44f24d27c6428d2a278',
    messagingSenderId: '867475044073',
    projectId: 'leaguepilot-e1c64',
    authDomain: 'leaguepilot-e1c64.firebaseapp.com',
    storageBucket: 'leaguepilot-e1c64.firebasestorage.app',
    measurementId: 'G-N1966B7ZBF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6CwvkYUUHVdGaIaPfjEcVdIe5HDDYGag',
    appId: '1:867475044073:android:e741295bb4f64b0ad2a278',
    messagingSenderId: '867475044073',
    projectId: 'leaguepilot-e1c64',
    storageBucket: 'leaguepilot-e1c64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2ciGYZynZ2XZfr77REbokXtOIlFXMIyc',
    appId: '1:867475044073:ios:03febf574d5deadfd2a278',
    messagingSenderId: '867475044073',
    projectId: 'leaguepilot-e1c64',
    storageBucket: 'leaguepilot-e1c64.firebasestorage.app',
    iosBundleId: 'com.example.hungerGames',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2ciGYZynZ2XZfr77REbokXtOIlFXMIyc',
    appId: '1:867475044073:ios:03febf574d5deadfd2a278',
    messagingSenderId: '867475044073',
    projectId: 'leaguepilot-e1c64',
    storageBucket: 'leaguepilot-e1c64.firebasestorage.app',
    iosBundleId: 'com.example.hungerGames',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrS9oAk8Myq2U-eyQQsKNlbAFdfqqbF5I',
    appId: '1:867475044073:web:2edc2a4b8f81e3b4d2a278',
    messagingSenderId: '867475044073',
    projectId: 'leaguepilot-e1c64',
    authDomain: 'leaguepilot-e1c64.firebaseapp.com',
    storageBucket: 'leaguepilot-e1c64.firebasestorage.app',
    measurementId: 'G-C7BP35EHPL',
  );

}