List<Map<String, String>> matchData = [
  {
    "status": "Live Now",
    "sport": "Cricket",
    "team_1_name": "IIT Ropar",
    "team_2_name": "IIT Kanpur",
    "team_1_score": "258",
    "team_2_score": "210",
    "date": "01/03/2025",
    "start_time": "13:50",
    "venue": "Cricket Ground"
  },
  {
    "status": "Upcoming",
    "sport": "Cricket",
    "team_1_name": "IIT Ropar",
    "team_2_name": "IIT Kanpur",
    "team_1_score": "-",
    "team_2_score": "-",
    "date": "12/03/2025",
    "start_time": "13:50",
    "venue": "Cricket Ground"
  },
  {
    "status": "Live Now",
    "sport": "Football",
    "team_1_name": "IIT Mandi",
    "team_2_name": "IIT Kanpur",
    "team_1_score": "2",
    "team_2_score": "1",
    "date": "01/03/2025",
    "start_time": "11:50",
    "venue": "Football Ground"
  },
  {
    "status": "Results",
    "sport": "Football",
    "team_1_name": "IIT Ropar",
    "team_2_name": "IIT Mandi",
    "team_1_score": "4",
    "team_2_score": "1",
    "date": "27/02/2025",
    "start_time": "13:50",
    "venue": "Cricket Ground",
    "Verdict": "IIT Ropar won by 3 goals."
  },
  {
    "status": "Upcoming",
    "sport": "Football",
    "team_1_name": "IIT Ropar",
    "team_2_name": "IIT Kanpur",
    "team_1_score": "-",
    "team_2_score": "-",
    "date": "01/03/2025",
    "start_time": "13:50",
    "venue": "Cricket Ground"
  },
  {
    "status": "Upcoming",
    "sport": "Basketball",
    "team_1_name": "IIT Ropar",
    "team_2_name": "IIT Mandi",
    "team_1_score": "-",
    "team_2_score": "-",
    "date": "05/03/2025",
    "start_time": "15:00",
    "venue": "Basketball Court"
  },
  {
    "status": "Live Now",
    "sport": "Badminton",
    "team_1_name": "IIT Kanpur",
    "team_2_name": "IIT Ropar",
    "team_1_score": "15",
    "team_2_score": "17",
    "date": "01/03/2025",
    "start_time": "10:30",
    "venue": "Badminton Court"
  },
  {
    "status": "Results",
    "sport": "Basketball",
    "team_1_name": "IIT Mandi",
    "team_2_name": "IIT Kanpur",
    "team_1_score": "55",
    "team_2_score": "48",
    "date": "28/02/2025",
    "start_time": "14:00",
    "venue": "Basketball Court",
    "Verdict": "IIT Mandi won by 7 points."
  },
  {
    "status": "Upcoming",
    "sport": "Volleyball",
    "team_1_name": "IIT Ropar",
    "team_2_name": "IIT Kanpur",
    "team_1_score": "-",
    "team_2_score": "-",
    "date": "06/03/2025",
    "start_time": "16:30",
    "venue": "Volleyball Court"
  },
  {
    "status": "Live Now",
    "sport": "Cricket",
    "team_1_name": "IIT Ropar",
    "team_2_name": "IIT Kanpur",
    "team_1_score": "258",
    "team_2_score": "210",
    "date": "01/03/2025",
    "start_time": "13:50",
    "venue": "Cricket Ground"
  },
  {
    "status": "Upcoming",
    "sport": "Cricket",
    "team_1_name": "IIT Ropar",
    "team_2_name": "IIT Kanpur",
    "team_1_score": "-",
    "team_2_score": "-",
    "date": "12/03/2025",
    "start_time": "13:50",
    "venue": "Cricket Ground"
  },
  {
    "status": "Live Now",
    "sport": "Football",
    "team_1_name": "IIT Mandi",
    "team_2_name": "IIT Kanpur",
    "team_1_score": "2",
    "team_2_score": "1",
    "date": "01/03/2025",
    "start_time": "11:50",
    "venue": "Football Ground"
  },
  {
    "status": "Results",
    "sport": "Football",
    "team_1_name": "IIT Ropar",
    "team_2_name": "IIT Mandi",
    "team_1_score": "4",
    "team_2_score": "1",
    "date": "27/02/2025",
    "start_time": "13:50",
    "venue": "Cricket Ground",
    "Verdict": "IIT Ropar won by 3 goals."
  },
  {
    "status": "Upcoming",
    "sport": "Football",
    "team_1_name": "IIT Ropar",
    "team_2_name": "IIT Kanpur",
    "team_1_score": "-",
    "team_2_score": "-",
    "date": "01/03/2025",
    "start_time": "13:50",
    "venue": "Cricket Ground"
  },
  {
    "status": "Upcoming",
    "sport": "Basketball",
    "team_1_name": "IIT Ropar",
    "team_2_name": "IIT Mandi",
    "team_1_score": "-",
    "team_2_score": "-",
    "date": "05/03/2025",
    "start_time": "15:00",
    "venue": "Basketball Court"
  },
  {
    "status": "Live Now",
    "sport": "Badminton",
    "team_1_name": "IIT Kanpur",
    "team_2_name": "IIT Ropar",
    "team_1_score": "15",
    "team_2_score": "17",
    "date": "01/03/2025",
    "start_time": "10:30",
    "venue": "Badminton Court"
  },
  {
    "status": "Results",
    "sport": "Basketball",
    "team_1_name": "IIT Mandi",
    "team_2_name": "IIT Kanpur",
    "team_1_score": "55",
    "team_2_score": "48",
    "date": "28/02/2025",
    "start_time": "14:00",
    "venue": "Basketball Court",
    "Verdict": "IIT Mandi won by 7 points."
  },
  {
    "status": "Upcoming",
    "sport": "Volleyball",
    "team_1_name": "IIT Ropar",
    "team_2_name": "IIT Kanpur",
    "team_1_score": "-",
    "team_2_score": "-",
    "date": "06/03/2025",
    "start_time": "16:30",
    "venue": "Volleyball Court"
  },
  {
    "status": "Upcoming",
    "sport": " Lawn Tennis",
    "team_1_name": "IIT Ropar",
    "team_2_name": "IIT Kanpur",
    "team_1_score": "-",
    "team_2_score": "-",
    "date": "08/03/2025",
    "start_time": "14:00",
    "venue": "Tennis Court"
  },
  {
    "status": "Live Now",
    "sport": "Lawn Tennis",
    "team_1_name": "IIT Mandi",
    "team_2_name": "IIT Kanpur",
    "team_1_score": "11",
    "team_2_score": "9",
    "date": "01/03/2025",
    "start_time": "12:30",
    "venue": "Table Tennis Court"
  },
  {
    "status": "Results",
    "sport": "Lawn Tennis",
    "team_1_name": "IIT Ropar",
    "team_2_name": "IIT Mandi",
    "team_1_score": "6",
    "team_2_score": "4",
    "date": "27/02/2025",
    "start_time": "14:00",
    "venue": "Tennis Court",
    "Verdict": "IIT Ropar won by 2 sets."
  },
  {
    "status": "Upcoming",
    "sport": "Badminton",
    "team_1_name": "IIT Kanpur",
    "team_2_name": "IIT Ropar",
    "team_1_score": "-",
    "team_2_score": "-",
    "date": "09/03/2025",
    "start_time": "17:00",
    "venue": "Badminton Court"
  },
  {
    "status": "Live Now",
    "sport": "Basketball",
    "team_1_name": "IIT Ropar",
    "team_2_name": "IIT Mandi",
    "team_1_score": "62",
    "team_2_score": "55",
    "date": "01/03/2025",
    "start_time": "14:30",
    "venue": "Basketball Court"
  },
  {
    "status": "Upcoming",
    "sport": "Football",
    "team_1_name": "IIT Kanpur",
    "team_2_name": "IIT Mandi",
    "team_1_score": "-",
    "team_2_score": "-",
    "date": "10/03/2025",
    "start_time": "16:00",
    "venue": "Football Ground"
  },
  {
    "status": "Live Now",
    "sport": "Cricket",
    "team_1_name": "IIT Ropar",
    "team_2_name": "IIT Kanpur",
    "team_1_score": "258",
    "team_2_score": "210",
    "date": "01/03/2025",
    "start_time": "13:50",
    "venue": "Cricket Ground"
  },
  {
    "status": "Upcoming",
    "sport": "Cricket",
    "team_1_name": "IIT Ropar",
    "team_2_name": "IIT Kanpur",
    "team_1_score": "-",
    "team_2_score": "-",
    "date": "12/03/2025",
    "start_time": "13:50",
    "venue": "Cricket Ground"
  },
  {
    "status": "Live Now",
    "sport": "Football",
    "team_1_name": "IIT Mandi",
    "team_2_name": "IIT Kanpur",
    "team_1_score": "2",
    "team_2_score": "1",
    "date": "01/03/2025",
    "start_time": "11:50",
    "venue": "Football Ground"
  },
  {
    "status": "Results",
    "sport": "Football",
    "team_1_name": "IIT Ropar",
    "team_2_name": "IIT Mandi",
    "team_1_score": "4",
    "team_2_score": "1",
    "date": "27/02/2025",
    "start_time": "13:50",
    "venue": "Cricket Ground",
    "Verdict": "IIT Ropar won by 3 goals."
  },
  {
    "status": "Upcoming",
    "sport": "Football",
    "team_1_name": "IIT Ropar",
    "team_2_name": "IIT Kanpur",
    "team_1_score": "-",
    "team_2_score": "-",
    "date": "01/03/2025",
    "start_time": "13:50",
    "venue": "Cricket Ground"
  },
  {
    "status": "Upcoming",
    "sport": "Basketball",
    "team_1_name": "IIT Ropar",
    "team_2_name": "IIT Mandi",
    "team_1_score": "-",
    "team_2_score": "-",
    "date": "05/03/2025",
    "start_time": "15:00",
    "venue": "Basketball Court"
  },
  {
    "status": "Live Now",
    "sport": "Badminton",
    "team_1_name": "IIT Kanpur",
    "team_2_name": "IIT Ropar",
    "team_1_score": "15",
    "team_2_score": "17",
    "date": "01/03/2025",
    "start_time": "10:30",
    "venue": "Badminton Court"
  },
  {
    "status": "Results",
    "sport": "Basketball",
    "team_1_name": "IIT Mandi",
    "team_2_name": "IIT Kanpur",
    "team_1_score": "55",
    "team_2_score": "48",
    "date": "28/02/2025",
    "start_time": "14:00",
    "venue": "Basketball Court",
    "Verdict": "IIT Mandi won by 7 points."
  },
  {
    "status": "Upcoming",
    "sport": "Volleyball",
    "team_1_name": "IIT Ropar",
    "team_2_name": "IIT Kanpur",
    "team_1_score": "-",
    "team_2_score": "-",
    "date": "06/03/2025",
    "start_time": "16:30",
    "venue": "Volleyball Court"
  },
  {
    "status": "Live Now",
    "sport": "Cricket",
    "team_1_name": "IIT Ropar",
    "team_2_name": "IIT Kanpur",
    "team_1_score": "258",
    "team_2_score": "210",
    "date": "01/03/2025",
    "start_time": "13:50",
    "venue": "Cricket Ground"
  },
  {
    "status": "Upcoming",
    "sport": "Cricket",
    "team_1_name": "IIT Ropar",
    "team_2_name": "IIT Kanpur",
    "team_1_score": "-",
    "team_2_score": "-",
    "date": "12/03/2025",
    "start_time": "13:50",
    "venue": "Cricket Ground"
  },
  {
    "status": "Live Now",
    "sport": "Football",
    "team_1_name": "IIT Mandi",
    "team_2_name": "IIT Kanpur",
    "team_1_score": "2",
    "team_2_score": "1",
    "date": "01/03/2025",
    "start_time": "11:50",
    "venue": "Football Ground"
  },
  {
    "status": "Results",
    "sport": "Football",
    "team_1_name": "IIT Ropar",
    "team_2_name": "IIT Mandi",
    "team_1_score": "4",
    "team_2_score": "1",
    "date": "27/02/2025",
    "start_time": "13:50",
    "venue": "Cricket Ground",
    "Verdict": "IIT Ropar won by 3 goals."
  },
  {
    "status": "Upcoming",
    "sport": "Football",
    "team_1_name": "IIT Ropar",
    "team_2_name": "IIT Kanpur",
    "team_1_score": "-",
    "team_2_score": "-",
    "date": "01/03/2025",
    "start_time": "13:50",
    "venue": "Cricket Ground"
  },
  {
    "status": "Upcoming",
    "sport": "Basketball",
    "team_1_name": "IIT Ropar",
    "team_2_name": "IIT Mandi",
    "team_1_score": "-",
    "team_2_score": "-",
    "date": "05/03/2025",
    "start_time": "15:00",
    "venue": "Basketball Court"
  },
  {
    "status": "Live Now",
    "sport": "Badminton",
    "team_1_name": "IIT Kanpur",
    "team_2_name": "IIT Ropar",
    "team_1_score": "15",
    "team_2_score": "17",
    "date": "01/03/2025",
    "start_time": "10:30",
    "venue": "Badminton Court"
  },
  {
    "status": "Results",
    "sport": "Basketball",
    "team_1_name": "IIT Mandi",
    "team_2_name": "IIT Kanpur",
    "team_1_score": "55",
    "team_2_score": "48",
    "date": "28/02/2025",
    "start_time": "14:00",
    "venue": "Basketball Court",
    "Verdict": "IIT Mandi won by 7 points."
  },
  {
    "status": "Upcoming",
    "sport": "Volleyball",
    "team_1_name": "IIT Ropar",
    "team_2_name": "IIT Kanpur",
    "team_1_score": "-",
    "team_2_score": "-",
    "date": "06/03/2025",
    "start_time": "16:30",
    "venue": "Volleyball Court"
  },
  {
    "status": "Upcoming",
    "sport": " Lawn Tennis",
    "team_1_name": "IIT Ropar",
    "team_2_name": "IIT Kanpur",
    "team_1_score": "-",
    "team_2_score": "-",
    "date": "08/03/2025",
    "start_time": "14:00",
    "venue": "Tennis Court"
  },
  {
    "status": "Live Now",
    "sport": "Lawn Tennis",
    "team_1_name": "IIT Mandi",
    "team_2_name": "IIT Kanpur",
    "team_1_score": "11",
    "team_2_score": "9",
    "date": "01/03/2025",
    "start_time": "12:30",
    "venue": "Table Tennis Court"
  },
  {
    "status": "Results",
    "sport": "Lawn Tennis",
    "team_1_name": "IIT Ropar",
    "team_2_name": "IIT Mandi",
    "team_1_score": "6",
    "team_2_score": "4",
    "date": "27/02/2025",
    "start_time": "14:00",
    "venue": "Tennis Court",
    "Verdict": "IIT Ropar won by 2 sets."
  },
  {
    "status": "Upcoming",
    "sport": "Badminton",
    "team_1_name": "IIT Kanpur",
    "team_2_name": "IIT Ropar",
    "team_1_score": "-",
    "team_2_score": "-",
    "date": "09/03/2025",
    "start_time": "17:00",
    "venue": "Badminton Court"
  },
  {
    "status": "Live Now",
    "sport": "Basketball",
    "team_1_name": "IIT Ropar",
    "team_2_name": "IIT Mandi",
    "team_1_score": "62",
    "team_2_score": "55",
    "date": "01/03/2025",
    "start_time": "14:30",
    "venue": "Basketball Court"
  },
  {
    "status": "Upcoming",
    "sport": "Football",
    "team_1_name": "IIT Kanpur",
    "team_2_name": "IIT Mandi",
    "team_1_score": "-",
    "team_2_score": "-",
    "date": "10/03/2025",
    "start_time": "16:00",
    "venue": "Football Ground"
  },
  {
    "status": "Live Now",
    "sport": "Cricket",
    "team_1_name": "IIT Ropar",
    "team_2_name": "IIT Kanpur",
    "team_1_score": "258",
    "team_2_score": "210",
    "date": "01/03/2025",
    "start_time": "13:50",
    "venue": "Cricket Ground"
  },
  {
    "status": "Upcoming",
    "sport": "Cricket",
    "team_1_name": "IIT Ropar",
    "team_2_name": "IIT Kanpur",
    "team_1_score": "-",
    "team_2_score": "-",
    "date": "12/03/2025",
    "start_time": "13:50",
    "venue": "Cricket Ground"
  },
  {
    "status": "Live Now",
    "sport": "Football",
    "team_1_name": "IIT Mandi",
    "team_2_name": "IIT Kanpur",
    "team_1_score": "2",
    "team_2_score": "1",
    "date": "01/03/2025",
    "start_time": "11:50",
    "venue": "Football Ground"
  },
  {
    "status": "Results",
    "sport": "Football",
    "team_1_name": "IIT Ropar",
    "team_2_name": "IIT Mandi",
    "team_1_score": "4",
    "team_2_score": "1",
    "date": "27/02/2025",
    "start_time": "13:50",
    "venue": "Cricket Ground",
    "Verdict": "IIT Ropar won by 3 goals."
  },
  {
    "status": "Upcoming",
    "sport": "Football",
    "team_1_name": "IIT Ropar",
    "team_2_name": "IIT Kanpur",
    "team_1_score": "-",
    "team_2_score": "-",
    "date": "01/03/2025",
    "start_time": "13:50",
    "venue": "Cricket Ground"
  },
  {
    "status": "Upcoming",
    "sport": "Basketball",
    "team_1_name": "IIT Ropar",
    "team_2_name": "IIT Mandi",
    "team_1_score": "-",
    "team_2_score": "-",
    "date": "05/03/2025",
    "start_time": "15:00",
    "venue": "Basketball Court"
  },
  {
    "status": "Live Now",
    "sport": "Badminton",
    "team_1_name": "IIT Kanpur",
    "team_2_name": "IIT Ropar",
    "team_1_score": "15",
    "team_2_score": "17",
    "date": "01/03/2025",
    "start_time": "10:30",
    "venue": "Badminton Court"
  },
  {
    "status": "Results",
    "sport": "Basketball",
    "team_1_name": "IIT Mandi",
    "team_2_name": "IIT Kanpur",
    "team_1_score": "55",
    "team_2_score": "48",
    "date": "28/02/2025",
    "start_time": "14:00",
    "venue": "Basketball Court",
    "Verdict": "IIT Mandi won by 7 points."
  },
  {
    "status": "Upcoming",
    "sport": "Volleyball",
    "team_1_name": "IIT Ropar",
    "team_2_name": "IIT Kanpur",
    "team_1_score": "-",
    "team_2_score": "-",
    "date": "06/03/2025",
    "start_time": "16:30",
    "venue": "Volleyball Court"
  },
  {
    "status": "Live Now",
    "sport": "Cricket",
    "team_1_name": "IIT Ropar",
    "team_2_name": "IIT Kanpur",
    "team_1_score": "258",
    "team_2_score": "210",
    "date": "01/03/2025",
    "start_time": "13:50",
    "venue": "Cricket Ground"
  },
  {
    "status": "Upcoming",
    "sport": "Cricket",
    "team_1_name": "IIT Ropar",
    "team_2_name": "IIT Kanpur",
    "team_1_score": "-",
    "team_2_score": "-",
    "date": "12/03/2025",
    "start_time": "13:50",
    "venue": "Cricket Ground"
  },
  {
    "status": "Live Now",
    "sport": "Football",
    "team_1_name": "IIT Mandi",
    "team_2_name": "IIT Kanpur",
    "team_1_score": "2",
    "team_2_score": "1",
    "date": "01/03/2025",
    "start_time": "11:50",
    "venue": "Football Ground"
  },
  {
    "status": "Results",
    "sport": "Football",
    "team_1_name": "IIT Ropar",
    "team_2_name": "IIT Mandi",
    "team_1_score": "4",
    "team_2_score": "1",
    "date": "27/02/2025",
    "start_time": "13:50",
    "venue": "Cricket Ground",
    "Verdict": "IIT Ropar won by 3 goals."
  },
  {
    "status": "Upcoming",
    "sport": "Football",
    "team_1_name": "IIT Ropar",
    "team_2_name": "IIT Kanpur",
    "team_1_score": "-",
    "team_2_score": "-",
    "date": "01/03/2025",
    "start_time": "13:50",
    "venue": "Cricket Ground"
  },
  {
    "status": "Upcoming",
    "sport": "Basketball",
    "team_1_name": "IIT Ropar",
    "team_2_name": "IIT Mandi",
    "team_1_score": "-",
    "team_2_score": "-",
    "date": "05/03/2025",
    "start_time": "15:00",
    "venue": "Basketball Court"
  },
  {
    "status": "Live Now",
    "sport": "Badminton",
    "team_1_name": "IIT Kanpur",
    "team_2_name": "IIT Ropar",
    "team_1_score": "15",
    "team_2_score": "17",
    "date": "01/03/2025",
    "start_time": "10:30",
    "venue": "Badminton Court"
  },
  {
    "status": "Results",
    "sport": "Basketball",
    "team_1_name": "IIT Mandi",
    "team_2_name": "IIT Kanpur",
    "team_1_score": "55",
    "team_2_score": "48",
    "date": "28/02/2025",
    "start_time": "14:00",
    "venue": "Basketball Court",
    "Verdict": "IIT Mandi won by 7 points."
  },
  {
    "status": "Upcoming",
    "sport": "Volleyball",
    "team_1_name": "IIT Ropar",
    "team_2_name": "IIT Kanpur",
    "team_1_score": "-",
    "team_2_score": "-",
    "date": "06/03/2025",
    "start_time": "16:30",
    "venue": "Volleyball Court"
  },
  {
    "status": "Upcoming",
    "sport": " Lawn Tennis",
    "team_1_name": "IIT Ropar",
    "team_2_name": "IIT Kanpur",
    "team_1_score": "-",
    "team_2_score": "-",
    "date": "08/03/2025",
    "start_time": "14:00",
    "venue": "Tennis Court"
  },
  {
    "status": "Live Now",
    "sport": "Lawn Tennis",
    "team_1_name": "IIT Mandi",
    "team_2_name": "IIT Kanpur",
    "team_1_score": "11",
    "team_2_score": "9",
    "date": "01/03/2025",
    "start_time": "12:30",
    "venue": "Table Tennis Court"
  },
  {
    "status": "Results",
    "sport": "Lawn Tennis",
    "team_1_name": "IIT Ropar",
    "team_2_name": "IIT Mandi",
    "team_1_score": "6",
    "team_2_score": "4",
    "date": "27/02/2025",
    "start_time": "14:00",
    "venue": "Tennis Court",
    "Verdict": "IIT Ropar won by 2 sets."
  },
  {
    "status": "Upcoming",
    "sport": "Badminton",
    "team_1_name": "IIT Kanpur",
    "team_2_name": "IIT Ropar",
    "team_1_score": "-",
    "team_2_score": "-",
    "date": "09/03/2025",
    "start_time": "17:00",
    "venue": "Badminton Court"
  },
  {
    "status": "Live Now",
    "sport": "Basketball",
    "team_1_name": "IIT Ropar",
    "team_2_name": "IIT Mandi",
    "team_1_score": "62",
    "team_2_score": "55",
    "date": "01/03/2025",
    "start_time": "14:30",
    "venue": "Basketball Court"
  },
  {
    "status": "Upcoming",
    "sport": "Football",
    "team_1_name": "IIT Kanpur",
    "team_2_name": "IIT Mandi",
    "team_1_score": "-",
    "team_2_score": "-",
    "date": "10/03/2025",
    "start_time": "16:00",
    "venue": "Football Ground"
  },
  {
    "status": "Live Now",
    "sport": "Cricket",
    "team_1_name": "IIT Ropar",
    "team_2_name": "IIT Kanpur",
    "team_1_score": "258",
    "team_2_score": "210",
    "date": "01/03/2025",
    "start_time": "13:50",
    "venue": "Cricket Ground"
  },
  {
    "status": "Upcoming",
    "sport": "Cricket",
    "team_1_name": "IIT Ropar",
    "team_2_name": "IIT Kanpur",
    "team_1_score": "-",
    "team_2_score": "-",
    "date": "12/03/2025",
    "start_time": "13:50",
    "venue": "Cricket Ground"
  },
  {
    "status": "Live Now",
    "sport": "Football",
    "team_1_name": "IIT Mandi",
    "team_2_name": "IIT Kanpur",
    "team_1_score": "2",
    "team_2_score": "1",
    "date": "01/03/2025",
    "start_time": "11:50",
    "venue": "Football Ground"
  },
  {
    "status": "Results",
    "sport": "Football",
    "team_1_name": "IIT Ropar",
    "team_2_name": "IIT Mandi",
    "team_1_score": "4",
    "team_2_score": "1",
    "date": "27/02/2025",
    "start_time": "13:50",
    "venue": "Cricket Ground",
    "Verdict": "IIT Ropar won by 3 goals."
  },
  {
    "status": "Upcoming",
    "sport": "Football",
    "team_1_name": "IIT Ropar",
    "team_2_name": "IIT Kanpur",
    "team_1_score": "-",
    "team_2_score": "-",
    "date": "01/03/2025",
    "start_time": "13:50",
    "venue": "Cricket Ground"
  },
  {
    "status": "Upcoming",
    "sport": "Basketball",
    "team_1_name": "IIT Ropar",
    "team_2_name": "IIT Mandi",
    "team_1_score": "-",
    "team_2_score": "-",
    "date": "05/03/2025",
    "start_time": "15:00",
    "venue": "Basketball Court"
  },
  {
    "status": "Live Now",
    "sport": "Badminton",
    "team_1_name": "IIT Kanpur",
    "team_2_name": "IIT Ropar",
    "team_1_score": "15",
    "team_2_score": "17",
    "date": "01/03/2025",
    "start_time": "10:30",
    "venue": "Badminton Court"
  },
  {
    "status": "Results",
    "sport": "Basketball",
    "team_1_name": "IIT Mandi",
    "team_2_name": "IIT Kanpur",
    "team_1_score": "55",
    "team_2_score": "48",
    "date": "28/02/2025",
    "start_time": "14:00",
    "venue": "Basketball Court",
    "Verdict": "IIT Mandi won by 7 points."
  },
  {
    "status": "Upcoming",
    "sport": "Volleyball",
    "team_1_name": "IIT Ropar",
    "team_2_name": "IIT Kanpur",
    "team_1_score": "-",
    "team_2_score": "-",
    "date": "06/03/2025",
    "start_time": "16:30",
    "venue": "Volleyball Court"
  },
  {
    "status": "Live Now",
    "sport": "Cricket",
    "team_1_name": "IIT Ropar",
    "team_2_name": "IIT Kanpur",
    "team_1_score": "258",
    "team_2_score": "210",
    "date": "01/03/2025",
    "start_time": "13:50",
    "venue": "Cricket Ground"
  },
  {
    "status": "Upcoming",
    "sport": "Cricket",
    "team_1_name": "IIT Ropar",
    "team_2_name": "IIT Kanpur",
    "team_1_score": "-",
    "team_2_score": "-",
    "date": "12/03/2025",
    "start_time": "13:50",
    "venue": "Cricket Ground"
  },
  {
    "status": "Live Now",
    "sport": "Football",
    "team_1_name": "IIT Mandi",
    "team_2_name": "IIT Kanpur",
    "team_1_score": "2",
    "team_2_score": "1",
    "date": "01/03/2025",
    "start_time": "11:50",
    "venue": "Football Ground"
  },
  {
    "status": "Results",
    "sport": "Football",
    "team_1_name": "IIT Ropar",
    "team_2_name": "IIT Mandi",
    "team_1_score": "4",
    "team_2_score": "1",
    "date": "27/02/2025",
    "start_time": "13:50",
    "venue": "Cricket Ground",
    "Verdict": "IIT Ropar won by 3 goals."
  },
  {
    "status": "Upcoming",
    "sport": "Football",
    "team_1_name": "IIT Ropar",
    "team_2_name": "IIT Kanpur",
    "team_1_score": "-",
    "team_2_score": "-",
    "date": "01/03/2025",
    "start_time": "13:50",
    "venue": "Cricket Ground"
  },
  {
    "status": "Upcoming",
    "sport": "Basketball",
    "team_1_name": "IIT Ropar",
    "team_2_name": "IIT Mandi",
    "team_1_score": "-",
    "team_2_score": "-",
    "date": "05/03/2025",
    "start_time": "15:00",
    "venue": "Basketball Court"
  },
  {
    "status": "Live Now",
    "sport": "Badminton",
    "team_1_name": "IIT Kanpur",
    "team_2_name": "IIT Ropar",
    "team_1_score": "15",
    "team_2_score": "17",
    "date": "01/03/2025",
    "start_time": "10:30",
    "venue": "Badminton Court"
  },
  {
    "status": "Results",
    "sport": "Basketball",
    "team_1_name": "IIT Mandi",
    "team_2_name": "IIT Kanpur",
    "team_1_score": "55",
    "team_2_score": "48",
    "date": "28/02/2025",
    "start_time": "14:00",
    "venue": "Basketball Court",
    "Verdict": "IIT Mandi won by 7 points."
  },
  {
    "status": "Upcoming",
    "sport": "Volleyball",
    "team_1_name": "IIT Ropar",
    "team_2_name": "IIT Kanpur",
    "team_1_score": "-",
    "team_2_score": "-",
    "date": "06/03/2025",
    "start_time": "16:30",
    "venue": "Volleyball Court"
  },
  {
    "status": "Upcoming",
    "sport": " Lawn Tennis",
    "team_1_name": "IIT Ropar",
    "team_2_name": "IIT Kanpur",
    "team_1_score": "-",
    "team_2_score": "-",
    "date": "08/03/2025",
    "start_time": "14:00",
    "venue": "Tennis Court"
  },
  {
    "status": "Live Now",
    "sport": "Lawn Tennis",
    "team_1_name": "IIT Mandi",
    "team_2_name": "IIT Kanpur",
    "team_1_score": "11",
    "team_2_score": "9",
    "date": "01/03/2025",
    "start_time": "12:30",
    "venue": "Table Tennis Court"
  },
  {
    "status": "Results",
    "sport": "Lawn Tennis",
    "team_1_name": "IIT Ropar",
    "team_2_name": "IIT Mandi",
    "team_1_score": "6",
    "team_2_score": "4",
    "date": "27/02/2025",
    "start_time": "14:00",
    "venue": "Tennis Court",
    "Verdict": "IIT Ropar won by 2 sets."
  },
  {
    "status": "Upcoming",
    "sport": "Badminton",
    "team_1_name": "IIT Kanpur",
    "team_2_name": "IIT Ropar",
    "team_1_score": "-",
    "team_2_score": "-",
    "date": "09/03/2025",
    "start_time": "17:00",
    "venue": "Badminton Court"
  },
  {
    "status": "Live Now",
    "sport": "Basketball",
    "team_1_name": "IIT Ropar",
    "team_2_name": "IIT Mandi",
    "team_1_score": "62",
    "team_2_score": "55",
    "date": "01/03/2025",
    "start_time": "14:30",
    "venue": "Basketball Court"
  },
  {
    "status": "Upcoming",
    "sport": "Football",
    "team_1_name": "IIT Kanpur",
    "team_2_name": "IIT Mandi",
    "team_1_score": "-",
    "team_2_score": "-",
    "date": "10/03/2025",
    "start_time": "16:00",
    "venue": "Football Ground"
  }

];
